# Generated by Django 4.0.1 on 2022-02-01 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_modified_data_movie_updated_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='updated_data',
            new_name='updated_date',
        ),
    ]
